version: '3.8'

services:
  app:
    build: .
    container_name: uas_cloud
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    container_name: laravel_pg
    environment:
      POSTGRES_DB: uas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 08595922708f
    ports:
      - "5432:5432"
