FROM php:8.3-fpm

# Install dependencies
RUN apt update && apt install -y \
    unzip \
    git \
    curl \
    libpq-dev \
    libzip-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    && docker-php-ext-install pdo pdo_pgsql zip mbstring

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

WORKDIR /var/www

COPY . .

# Jalankan composer install
RUN composer install

# Generate key dan cache config (opsional)
# RUN php artisan key:generate && php artisan config:cache

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
